### ISSUE TITLE
Empty space after footcite number

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#87]
## Description

There should be no empty space after a footcite number.

## How to reproduce

1. Code example: `von HTTP/2 (\ac{RFC} 7540 \ifootcite[4]{ietf_rfc7540}) einhergehen.`

## Screenshots

![grafik](https://user-images.githubusercontent.com/13857929/78116907-433dbf00-7405-11ea-8b8d-a74c27e2b07e.png)

**Comment by robingenz** [comment]
Another example:
![grafik](https://user-images.githubusercontent.com/13857929/78119425-b137b580-7408-11ea-978b-13c96dc4be2a.png)

Code: 
```
Aktualisierungen: \ac{RFC} 7936\ifootcite[4]{ietf_rfc7936}, \ac{RFC} 8307\ifootcite[4]{ietf_rfc8307} und \ac{RFC} 8441\ifootcite[4]{ietf_rfc8441}.
```

**Comment by skyfrk** [comment]
This behaviour is intended (at least by LaTeX, not by me 🙈) because a footnote mark is normally at the end of a sentence, which is always followed by same space before the next sentence starts. See this example here:

![image](https://user-images.githubusercontent.com/27026029/78135289-ee5c7180-7421-11ea-82d2-b58bff8db368.png)

So if you want to use a footnotemark mid-sentence it obviously looks bad. But we can fix it using `\unskip`!

```tex
This is the normal use case.\ifootcite{ref} This is not the normal use case (because the footecite command is directly followed by a character\ifootcite{ref}\unskip).
```
![image](https://user-images.githubusercontent.com/27026029/78135404-2368c400-7422-11ea-8589-ed49f9f96d73.png)

Maybe there is a even smarter workaround. I don't know 🤷‍♂️.

It think we should document this.... 😬

**Comment by robingenz** [comment]
And again, thank you! 😄
